# 应用名称
spring:
  profiles:
    active: dev

  application:
    name: scaffold
#  datasource:
#    url: jdbc:mysql://${MYSQL_IP}:${MYSQL_PORT}/${spring.application.name}
#    username: ${MYSQL_USER}
#    password: ${MYSQL_SECRET}
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
  rabbitmq:
    host: ${RABBIT_MQ_IP}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual # 手动应答
        concurrency: 5 # 消费端最小并发数
        max-concurrency: 10 # 消费端最大并发数
        prefetch: 5 # 一次请求中预处理的消息数量
    cache:
      channel:
        size: 50 # 缓存的channel数量
# 应用服务 WEB 访问端口
server:
  port: 8080

service:
  ip2region:
    store: /opt/store/ip2region.db

scaffold:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5000
      - https://console.pepaya.vip

mq:
  default-exchange: amqpExchange # 默认交换器
  queue: queue # 队列名
  route-key: queue_key # 路由key

#minio:
#  endpoint: http://172.16.3.28:10000
#  accessKey: admin
#  secretKey: 12345678
#  bucketName: aaa