host: 10.1.20.112
server:
  port: 8066
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /scaffold

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: scaffold
  datasource:
    name: druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      primary:
        url: jdbc:mysql://${host}:3306/scaffold?autoRec&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
        username: root
        password: vgy87dgy16rhd61fAGHbcgA
      secondary:
        url: jdbc:mysql://aries.remote:3306/polaris?useUnicode=true?characterEncoding=utf-8&serverTimezone=GMT%2b8
        username: root
        password: vgy87dgy16rhd61fAGHbcgA
      initial-size: 2
      min-idle: 5
      max-active: 10
      max-wait: 5000
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
      web-stat-filter:
        enabled: true
        exclusions: js,gif,jpg,png,css,ico,/druid/*
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: druid2021
  redis:
    host: aries.remote
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20
        max-wait: 1ms
        max-idle: 5
        min-idle: 0
    timeout: 10000
  cache:
    redis:
      time-to-live: 3d
      use-key-prefix: true
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        session_factory:
  servlet:
    multipart:
      max-file-size: 100MB #单个文件的最大上限
      max-request-size: 100MB #单个请求的文件总大小上限
  data:
    redis:
      repositories:
        enabled: false

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.data.mongodb.core: DEBUG
  config: classpath:log4j2-spring.xml

minio:
  endpoint: http://127.0.0.1:9001
  accessKey: miniouser
  secretKey: 123456
  bucket: data

swagger:
  enable: true
  title: 自定义脚手架
  description: 自定义脚手架文档
  service-url: 115.156.248.127
  version: 0.1


