server:
  port: 8096

spring:
  application:
    name: scaffold-test-postgresql-cache
  datasource:
    url: jdbc:postgresql://localhost:5432/aries
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never

scaffold:
  cache:
    postgresql:
      table-name: scaffold_spring_cache
      default-ttl: 3d
      initialize-schema: true
      cleanup-on-startup: true
      scheduled-cleanup: true
      cleanup-interval: 5m
