# 优雅停机，这能保证服务停止时，不再接收新请求，但会处理完当前正在进行的请求，避免用户操作中断。
server:
  shutdown: graceful
  port: 8082
spring:
  application:
    name: scaffold-biz
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cache:
    # 最小演示使用caffeine内存缓存更方便
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=10m
  freemarker:
    check-template-location: false
  datasource:
#    driver-class-name: ${SCAFFOLD_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
#    url: ${SCAFFOLD_DATASOURCE_URL:jdbc:mysql://localhost:3306/scaffold?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true}
#    username: ${SCAFFOLD_DATASOURCE_USERNAME:root}
#    password: ${SCAFFOLD_DATASOURCE_PASSWORD:123456}
    # 演示模式使用h2数据库，
    url: ${SCAFFOLD_DATASOURCE_URL:jdbc:h2:file:~/scaffold-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE}
    username: ${SCAFFOLD_DATASOURCE_USERNAME:root}
    password: ${SCAFFOLD_DATASOURCE_PASSWORD:123456}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        transaction:
          coordinator_class: jdbc
          jta:
            platform: ""
    database-platform: org.hibernate.dialect.H2Dialect

# 文档默
swagger:
  enabled: true

scaffold:
  # web配置
  web:
    response:
      raw-body-path-patterns:
        - /actuator
        - /actuator/**
        - /codegen/configs/*/download
        - /codegen/tables/*/download
  # 权限配置
  security:
    token:
      cache-ttl: 30m
      cache-maximum-size: 10000
    cors:
      enabled: true
      allowed-origin-patterns:
        - "http://localhost:*"
        - "http://127.0.0.1:*"
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      allowed-headers:
        - "*"
  # 文件存储，演示模式默认使用本地存储方式
  file-storage:
    enabled: true
    type: local
    local:
      base-path: /Users/aries/Documents/www
#       base-path: ${SCAFFOLD_FILE_STORAGE_BASE_PATH:./.data/files}
#  file-storage:
#    enabled: true
#    type: s3
#    s3:
#      endpoint: http://127.0.0.1:9000
#      access-key: minioadmin
#      secret-key: minioadmin
#      bucket-name: scaffold