#!/usr/bin/env bash
set -euo pipefail

BUNDLE_DIR="$(cd "${1:-.}" && pwd)"
HOST_PORT="${2:-8093}"
CONTAINER_NAME="${QWEN3_ASR_CONTAINER_NAME:-qwen3-asr}"

for file in image.tar.gz bundle.env; do
  [[ -f "$BUNDLE_DIR/$file" ]] || { echo "Missing bundle file: $BUNDLE_DIR/$file" >&2; exit 2; }
done

if [[ -f "$BUNDLE_DIR/SHA256SUMS" ]]; then
  echo "Verifying bundle checksums ..."
  if command -v sha256sum >/dev/null 2>&1; then
    (cd "$BUNDLE_DIR" && sha256sum -c SHA256SUMS)
  else
    (cd "$BUNDLE_DIR" && shasum -a 256 -c SHA256SUMS)
  fi
fi

# bundle.env is generated by export-offline-bundle.sh and only contains validated values.
source "$BUNDLE_DIR/bundle.env"

case "$(uname -m)" in
  x86_64) HOST_ARCH=amd64 ;;
  arm64|aarch64) HOST_ARCH=arm64 ;;
  *) echo "Unsupported host architecture: $(uname -m)" >&2; exit 2 ;;
esac
[[ "$HOST_ARCH" == "$ARCH" ]] || { echo "Bundle architecture is $ARCH, host is $HOST_ARCH" >&2; exit 2; }

if docker container inspect "$CONTAINER_NAME" >/dev/null 2>&1; then
  echo "Container already exists: $CONTAINER_NAME" >&2
  exit 2
fi

echo "Loading Docker image ..."
gzip -dc "$BUNDLE_DIR/image.tar.gz" | docker load

DOCKER_ARGS=(
  run -d
  --name "$CONTAINER_NAME"
  --restart unless-stopped
  --shm-size 4g
  -p "$HOST_PORT:8093"
)
if [[ "$VARIANT" == "gpu" ]]; then
  DOCKER_ARGS+=( --gpus all )
fi
DOCKER_ARGS+=( "$IMAGE_TAG" )

docker "${DOCKER_ARGS[@]}"
echo "Qwen3-ASR is starting at http://127.0.0.1:$HOST_PORT/qwen3-asr/health"
