host: 10.1.20.112
server:
  port: 8067
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /scaffold

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: hnc-machineassembly-api-service-dev-local
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${MYSQL_IP}:3306/hzsk_dev?autoRec&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: ${MYSQL_PASSWD}
    secondary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${MYSQL_IP}:3306/iNC_HealthDataIndex?useUnicode=true?characterEncoding=utf-8&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
      username: root
      password: ${MYSQL_PASSWD}
    td:
      driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
      jdbc-url: jdbc:TAOS-RS://${TAOS_IP}:6041/scaffold?useUnicode=true?characterEncoding=utf-8&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
      username: root
      password: taosdata
  redis:
    host: ${REDIS_IP}
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: 1ms
        max-idle: 5
        min-idle: 0
    timeout: 10000
  cache:
    redis:
      time-to-live: 3d
      use-key-prefix: true
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        session_factory:
        #statement_inspector: cn.hzncc.machineassembly.config.interceptor.JpaInspector
  servlet:
    multipart:
      max-file-size: 100MB #单个文件的最大上限
      max-request-size: 100MB #单个请求的文件总大小上限


logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
  config: classpath:log4j2-spring.xml

swagger:
  enable: true
  title: 四位一体文档
  description: 四位一体各接口Swagger文档
  service-url: 10.10.33.69
  version: 1.3.0


minio:
  endpoint: http://10.1.20.115:8071
  accessKey: miniouser
  secretKey: miniosciDAVC
  bucket: data

double-cache:
  allow-null: true
  init: 100
  max: 1000
  expire-after-write: 1000
  expire-after-access: 1000
  refresh-after-write: 1000
  redis-expire: 1000

rocketmq:
  name-server: ${ROCKETMQ_URL}
  producer:
    group: Pro_Group
    send-message-timeout: 3000
    retry-times-when-send-async-failed: 3

#easy-es:
#  enable: true #默认为true,若为false则认为不启用本框架
#  address : 127.0.0.1:9200 # es的连接地址,必须含端口 若为集群,则可以用逗号隔开 例如:127.0.0.1:9200,127.0.0.2:9200
#  username: elastic #若无 则可省略此行配置
#  password: WG7WVmuNMtM4GwNYkyWH #若无 则可省略此行配置
#

