spring:
  application:
    name: cloud-gateway-10000
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:123456}
    sentinel:
      transport:
        dashboard: ${SENTINEL_DASHBOARD:localhost:8858}
      eager: true
    gateway:
      server:
        webflux:
          routes:
            - id: cloud-auth-10080
              uri: lb://cloud-auth-10080
              predicates:
                - Path=/auth/**
            - id: cloud-provider-10881
              uri: lb://cloud-provider-10881
              predicates:
                - Path=/provider/**
              filters:
                - StripPrefix=1
            - id: cloud-consumer-10082
              uri: lb://cloud-consumer-10082
              predicates:
                - Path=/consumer/**
              filters:
                - StripPrefix=1
            - id: cloud-order-10083
              uri: lb://cloud-order-10083
              predicates:
                - Path=/order/**
              filters:
                - StripPrefix=1

server:
  port: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,prometheus
  tracing:
    propagation:
      type: w3c
    sampling:
      probability: 1.0
logging:
  pattern:
    level: "%5p [traceId=%X{traceId:-}, spanId=%X{spanId:-}]"
